"""add_user_id_to_trainings

Revision ID: 9ab0cf837b63
Revises: fefe1dbc2e25
Create Date: 2025-04-11 11:35:08.570577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab0cf837b63'
down_revision = 'fefe1dbc2e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'trainings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_column('trainings', 'user_id')
    # ### end Alembic commands ###
