name: ed-std

services:
  db:
    container_name: ed_std_db
    image: postgres:16
    restart: always
    ports:
      - "5436:5432" # port重複防止のため、local側は5432以外とする
    environment:
      POSTGRES_DB: baseball_note
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    networks:
      - fastapi_network
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d baseball_note"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_db:
    container_name: ed_std_test_db
    image: postgres:16
    restart: always
    ports:
      - "5437:5432" # テスト用のポート
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - fastapi_network
    volumes:
      - test_db_volume:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: ed_std_web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SQLALCHEMY_WARN_20: 1
      DATABASE_URL: "postgresql://docker:docker@db:5432/baseball_note"
      FIREBASE_STORAGE_BUCKET: "web-baseball.firebasestorage.app"
    healthcheck:
      test: "curl -f http://localhost:80/docs || exit 1"
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
      test_db:
        condition: service_healthy
    command: [
        "/bin/sh",
        "-c",
        "alembic upgrade heads && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload --log-config ./app/logger_config.yaml --proxy-headers --forwarded-allow-ips='*'"
    ]
    ports:
      - 8080:80
      - 8081:81 # for debug launch
    volumes:
      - .:/backend
      - /backend/.venv
      - ./uploads:/backend/uploads  # アップロードディレクトリのマウントを追加
      - ./.firebase-service-account-key:/backend/app/.firebase-service-account-key.json
    links:
      - db
    restart: always
    networks:
      - fastapi_network

volumes:
  db_volume:
    driver: local
  test_db_volume:
    driver: local
  uploads_volume:  # 新しいボリュームを追加
    driver: local


networks:
  fastapi_network:
    name: fastapi_network
    driver: bridge
